#!/bin/bash
# Docker funcs


export DOCKER_REPO_PREFIX=mcrmonkey

dcleanup(){
    local containers
    local volumes
    local images

    containers=( $(docker ps -aq 2>/dev/null) )
    volumes=( $(docker ps --filter status=exited -q 2>/dev/null) )
    images=( $(docker images --filter dangling=true -q 2>/dev/null) )

    docker rm "${containers[@]}" 2>/dev/null
    docker rm -v "${volumes[@]}" 2>/dev/null
    docker rmi "${images[@]}" 2>/dev/null

    docker system prune -f --volumes
}

divetool() {
	docker run --rm -it \
		-v /usr/bin/docker:/bin/docker:ro \
		-v /var/run/docker.sock:/var/run/docker.sock \
		-v "$HOME/.dive.yaml":"$HOME/.dive.yaml" \
		-v "$(pwd)":"$(pwd)" \
		-w "$(pwd)" \
		wagoodman/dive:latest ${@}
}



dockertop() {
    docker stats --format "table {{.Container}}\t{{.Name}}\t{{.CPUPerc}}  {{.MemPerc}}\t{{.NetIO}}\t{{.BlockIO}}"
}


alias alpine='docker run -it --rm alpine /bin/sh'
alias centos='docker run -it --rm centos:7 /bin/bash'
alias debjess='docker run -it --rm debian:jessie /bin/bash'
alias stretch='docker run -it --rm debian:stretch /bin/bash'
alias buster='docker run -it --rm debian:buster /bin/bash'
alias bullseye='docker run -it --rm debian:bullseye /bin/bash'

