#!/bin/bash

show_usage() {
	echo -ne "\nRepo installer\n"
	echo "$0 <repo to setup>"
	echo "Repo's:"
	echo "gcp - Google Cloud SDK"
	echo "gchrome - Google Chrome"
	echo "docker"
	echo "virtualbox"
	echo "spotify"
}


case "$1" in
	gcp)
		# Add the Cloud SDK distribution URI as a package source
		echo "deb https://packages.cloud.google.com/apt cloud-sdk main" > /etc/apt/sources.list.d/google-cloud-sdk.list
		# Import the Google Cloud Platform public key
		curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
		;;
	gchrome)
		echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list
		curl https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
		;;
	docker)
		echo "docker"
		apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common
		curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
		echo "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
		;;
	spotify)
		sudo echo "deb http://repository.spotify.com stable non-free" > /etc/apt/sources.list.d/spotify.list
		sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
		echo "spotify-client: done but may need some weird dep"
		;;
	virtualbox)
		echo "deb http://download.virtualbox.org/virtualbox/debian stretch contrib" > /etc/apt/sources.list.d/virtualbox.list
		curl https://www.virtualbox.org/download/oracle_vbox_2016.asc |apt-key add -
		;;
	*)
		show_usage
		exit 1
esac

echo "run update before install"
